# Change these first
owner: tigefa4u # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository
user-agent: tigefa4u

sites:
  - name: Tigefa
    url: https://tigefa.com
    icon: https://tigefa.com/favicon.ico
  - name: Tigefa Neet
    url: https://tigefa.net
    icon: https://tigefa.net/favicon.ico
  - name: Minio
    url: https://tigefa.site
  - name: Tigefa.win
    url: https://tigefa.win
    icon: https://tigefa.win/favicon.ico
  - name: Tigefa.pw
    url: https://tigefa.pw
    icon: https://tigefa.pw/favicon.ico
  - name: Tigefa blog
    url: https://tigefa.my.id
    icon: https://tigefa.my.id/favicon.ico
  - name: Plausible
    url: https://plausible.my.id
  - name: PrivateBin
    url: https://privatebin.my.id
  - name: Yourls
    url: https://urls.my.id
  - name: tgfa.my.id
    url: https://tgfa.my.id
  - name: cURLs.top
    url: https://curls.top 
  - name: Kodev
    url: https://kodev.my.id

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.tigefa.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Tigefa Status
  theme: night
  customHeadHtml: "<script defer data-domain='tigefa.com' src='https://plausible.my.id/js/plausible.js'></script>"
#  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
#  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: Tigefa
      href: https://tigefa.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
workflowSchedule:
  graphs: "*/15 * * * *"
  responseTime: "*/10 * * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

commitMessages:
  commitAuthorName: "Tigefa Bot"
  commitAuthorEmail: "tigefabot@gmail.com"
